apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-wordpress-dev
